### ISSUE TITLE
Fix common-styles to v1.0.0

### ISSUE THREAD

**Issue by ghislaineguerin** [Rise-Vision/developer-hub#32]

**Comment by ByronDarlison** [comment]
@ghislaineguerin is this issue still open and if it is, what's the problem that needs to be solved and who should own it?

**Comment by ByronDarlison** [comment]
@ghislaineguerin can you let us know about this defect. I'd like to get it closed or queued up.

**Comment by ghislaineguerin** [comment]
@ByronDarlison no longer needed.
