### ISSUE TITLE
Call using core.company.add doesn't get counted as a call in the UI

### ISSUE THREAD

**Issue by AlexKolenoff** [Rise-Vision/developer-hub#39]
I did a call to core.api using http://rise-vision.github.io/core-api/ / core.company.add, and 
then looked at the results here (Sample Code API Explorer): http://developer.stage.risevision.com/#/apps/list, but the call was never counted.

Note that when I did the call with core.company.add, I didn't add any data but just clicked Execute and got an error - http://screencast.com/t/f2xXMzPi - however, Rodrigo said that it should still be a valid call and should be counted (yet it was not).

**Comment by rodrigopavezi** [comment]
@AlexKolenoff I have investigated this and I found out that the monitoring filter is not able to count requests which have a HTTP 400 error code (Bad Request). The server does not even process the request so it stops it and sends a error response to the client before anything happens on the server. I think we shouldn't be looking to count such requests as they don't use our server processing resources. Neither google can get much info about this king of requests as we can see on the below log message.

![screen shot 2015-02-13 at 6 08 05 pm](https://cloud.githubusercontent.com/assets/1659305/6194429/6d74489a-b3ab-11e4-9bbf-670f3d0abd98.png)

I suggest we close this issue. Do you agree? 

Thanks.

**Comment by AlexKolenoff** [comment]
Agreed.  Thanks Rodrigo.
