### ISSUE TITLE
When field string is added to API Explorer, no results are provided.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/developer-hub#58]
**How to recreate**
1. Access the API Explorer: https://developer.risevision.com/api-explorer/core.company.get?cid=f114ad26-949d-44b4-87e9-8528afc76ce4
2. Following the instructions at https://help.risevision.com/developer/core-api/company/core.company.get add strings to the "fields" field.

**What happens**
Nothing is returned when there are strings specified in "fields"

https://www.screencast.com/t/3Fpq5ADVEuD

**Comment by ezequielc** [comment]
@btfrise I did a quick review of the issue and it actually works fine. The value you entered in "fields" is not correct. It should be "item(id, parentId)" as there is an "item" parent element in the response.
As it works fine, I will close the issue, but I will add a card to improve documentation to make this clear. Thanks!
